
//------------------------------------------------------------------
//  **MEDYAN** - Simulation Package for the Mechanochemical
//               Dynamics of Active Networks, v4.0
//
//  Copyright (2015-2018)  Papoian Lab, University of Maryland
//
//                 ALL RIGHTS RESERVED
//
//  See the MEDYAN web page for more information:
//  http://www.medyan.org
//------------------------------------------------------------------

#ifndef MEDYAN_Filament_h
#define MEDYAN_Filament_h

#include <vector>
#include <iostream>
#include <deque>
#include <cmath>

#include "common.h"

#include "Database.h"
#include "Histogram.h"
#include "Trackable.h"
#include "Composite.h"
#include "RestartParams.h"

namespace medyan {

//FORWARD DECLARATIONS
class SubSystem;
class Cylinder;
class Bead;

/// Used to store data about connectivity of [Cylinders](@ref Cylinder) and [Beads] (@ref Bead).
/*!
 * This class contains information about [Cylinders](@ref Cylinder) and [Beads]
 * (@ref Bead) connectivity. It has functionality to polymerize and depolymerize,
 * as well as extend and retract by creating and deleting Cylinder and Bead in the 
 * system.
 *
 * Extending the Trackable class, all instances are kept and 
 * easily accessed by the SubSystem.
 * 
 * A Filament can also be initialized as a number of different shapes.
 * 
 * 
 * The positional index used in a filament
 * 
 *                      (-) |-----------|------------------|------------------|-----| (+)
 * Cylinder position        |    -2     |        -1        |        0         |  1  |
 * Bead position            -2          -1                 0                  1     2
 * 
 */
class Filament : public Composite, public Trackable,
    public Database< Filament, false > {

private:
    /// Deque of cylinders
    /// @note - the "front" of this deck is the minus end of the filament.
    deque<Cylinder*> _cylinderVector;

    SubSystem* _subSystem; ///< SubSystem pointer
    
    short _filType; ///< Filament type
    
    vector<int> _severingID;      ///ID of a new filament generated by severing
    
    short _deltaPlusEnd = 0;   ///< Change in filament's cylinders
                               ///< at plus end since last snapshot
    short _deltaMinusEnd = 0;  ///< Change in filament's cylinders
                               ///< at minus end since last snapshot
    
    short _polyPlusEnd = 0;    ///< Change in corresponding reaction
    short _polyMinusEnd = 0;   ///< since last snapshot
    short _depolyPlusEnd = 0;
    short _depolyMinusEnd = 0;
    short _nucleationReaction = 0;
    short _severingReaction = 0;
    
    int _plusEndPosition   = 0;  ///< Position of plus end bead at last turnover
    floatingpoint _turnoverTime   = 0;  ///< Time since last turnover

    //@{
    ///Histogram data
    static Histogram* _turnoverTimes;
    //@}
    
public:
    /// This constructor creates a short filament, containing only two beads, at runtime.
    /// Coordinates of the first bead is an input, second is set up by using an input
    /// direction. Using all this, two constructors for beads and cylinders are called.
    /// @param nucleation - this filament was nucleated at runtime by a non-branching species
    /// @param branching - this filament was branched at runtime from an existing filament
	Filament(SubSystem* s, short filamentType,
                           const vector<floatingpoint>& position,
                           const vector<floatingpoint>& direction,
                           bool nucleation = false,
                           bool branch = false);
    
    /// This constructor is called to create a filament at startup. It creates a filament
    /// with a number of beads numBeads. Filaments starts and ends in the point
    /// determined by position vector.
    Filament(SubSystem* s, short filamentType,
             const std::vector<Vec<3, FP>>& position, int numBeads,
             const SimulConfig& conf,
             string projectionType = "STRAIGHT");
    
    /// This constructor is called when a filament is severed. It creates a filament
    /// that initially has no cylinders.
    Filament(SubSystem* s, short filamentType)
        : Trackable(), _subSystem(s), _filType(filamentType) {}
    
    /// This destructor is called when a filament is to be removed from the system.
    /// Removes all cylinders and beads associated with the filament.
    ~Filament();
    
    /// Addition of a new cylinder. Next position is based on previous beads directions
    /// in the filament. This function creates a new bead. So, this function is mostly
    /// called during further extension, not initiation.
    /// @param plusEnd - the plus end species to be marked. Only if doing chemistry.
    void extendPlusEnd(short plusEnd);
    /// Same as extension front, but adds a new first cylinder with first bead = new
    /// bead and a second bead is equal to the first bead in the cylinder, which used
    /// to be first.
    /// @param minusEnd - the minus end species to be marked. Only if doing chemistry.
    void extendMinusEnd(short minusEnd);
    
    ///Extend, used for initialization
    void extendPlusEnd(const Vec<3, FP>& coordinates);
    void extendMinusEnd(const Vec<3, FP>& coordinates);
    
    /// Retraction of front of a cylinder. Removes one cylinder and one bead from the
    /// front of filament.
    void retractPlusEnd();
    /// Retraction of back of a cylinder. Removes a cylinder and bead from back of
    /// filament.
    void retractMinusEnd();
    
    /// Polymerization of a filament front, which moves the leading bead one monomer
    /// length. Updates cylinder parameters accordingly.
    void polymerizePlusEnd();
    /// Same as Polymerization front, but moves the back bead one monomer length, and
    /// updates cylinder parameters accordingly.
    void polymerizeMinusEnd();
    
    /// Depolymerization of a filament front, which moves the leading bead back one
    /// monomer length. Updates cylinder parameters accordingly.
    void depolymerizePlusEnd();
    /// Same as depolymerization front, but moves the back bead forward one monomer
    /// length. Updates cylinder parameters accordingly.
    void depolymerizeMinusEnd();
    
    /// Initialize the nucleation of a new filament
    /// Initializes all chemical species in initial Cylinder
    void nucleate(short plusEnd, short filament, short minusEnd);
    
    /// Sever a filament at a given cylinder position. The back part of the filament
    /// will remain as this (original) filament, and the new filament, which is
    /// the front part of the originally severed filament, will be returned.
    // Note: the actual sever point is the minus end of the given cylinder.
    Filament* sever(int cylinderPosition);
    
    /// Get vector of cylinders that this filament contains.
    auto& getCylinderVector()       { return _cylinderVector; }
    auto& getCylinderVector() const { return _cylinderVector; }
    
    //@{
    /// Get / reset temporary counters
    void resetDeltaPlusEnd() {_deltaPlusEnd = 0;}
    void resetDeltaMinusEnd() {_deltaMinusEnd = 0;}
    short getDeltaPlusEnd() const {return _deltaPlusEnd;}
    short getDeltaMinusEnd() const {return _deltaMinusEnd;}

    short getPolyPlusEnd() {return _polyPlusEnd;}
    void resetPolyPlusEnd() { _polyPlusEnd = 0;}

    short getPolyMinusEnd() {return _polyMinusEnd;}
    void resetPolyMinusEnd() { _polyMinusEnd = 0;}

    short getDepolyPlusEnd() {return _depolyPlusEnd;}
    void resetDepolyPlusEnd() { _depolyPlusEnd = 0;}

    short getDepolyMinusEnd() {return _depolyMinusEnd;}
    void resetDepolyMinusEnd() { _depolyMinusEnd = 0;}

    short getNucleation() {return _nucleationReaction;}
    void resetNucleation() { _nucleationReaction = 0;}

    void resetCounters() {
        resetDeltaPlusEnd();
        resetDeltaMinusEnd();
        resetPolyPlusEnd();
        resetPolyMinusEnd();
        resetDepolyPlusEnd();
        resetDepolyMinusEnd();
        resetNucleation();
        resetSevering();
        resetSeveringID();
    }
    //@}
    
    short getSevering() {return _severingReaction;}
    void resetSevering() { _severingReaction = 0;}
    vector<int> getNewID() {return _severingID;};
    void resetSeveringID() {_severingID.clear();}
    //@}
    
    /// Get type
    int getType() {return _filType;}
    auto getType() const { return _filType; }
    
    //@{
    /// Get end cylinder
    Cylinder* getMinusEndCylinder() {return _cylinderVector.front();}
    Cylinder* getPlusEndCylinder() {return _cylinderVector.back();}
    //@}
    
    //@{
    /// SubSystem management, inherited from Trackable
    // Does nothing
    virtual void addToSubSystem() override { }
    virtual void removeFromSubSystem() override {}
    //@}
    
    /// Get all instances of this class from the SubSystem
    static const vector<Filament*>& getFilaments() {
        return getElements();
    }
    /// Get the number of filaments in this system
    static int numFilaments() {
        return getElements().size();
    }
    /// Get the turnover times
    static Histogram* getTurnoverTimes() {return _turnoverTimes;}
    
    //@{
    /// Projection function, returns a vector of coordinates for bead creation
    vector<floatingpoint> nextBeadProjection(Bead* b, floatingpoint d, vector<floatingpoint> director);
    
    std::vector<Vec<3, FP>> straightFilamentProjection(const Vec<3, FP>& v1, const Vec<3, FP>& v2, int numBeads, FP cylLength);
    std::vector<Vec<3, FP>> zigZagFilamentProjection(const Vec<3, FP>& v1, const Vec<3, FP>& v2, int numBeads, FP cylLength);
    std::vector<Vec<3, FP>> arcFilamentProjection(const Vec<3, FP>& v1, const Vec<3, FP>& v2, int numBeads);

    //To initialize filaments with cylinders during restart.
	void initializerestart(vector<Cylinder*> cylindervector, vector<restartCylData>&
	_rCDatavec);

    virtual void printSelf()const;
    
    /// Check the consistency of the filament. For now,
    /// Mainly involves checking chemistry of the constituent cylinders.
    bool isConsistent();
    
    /// Count the number of filament species with a given name in the system
    static species_copy_t countSpecies(short filamentType, const string& name);

    static floatingpoint FilextendPlusendtimer1;
    static floatingpoint FilextendPlusendtimer2;
    static floatingpoint FilextendPlusendtimer3;
	static floatingpoint FilextendMinusendtimer1;
	static floatingpoint FilextendMinusendtimer2;
	static floatingpoint FilextendMinusendtimer3;
};

} // namespace medyan

#endif
